### ISSUE TITLE
A Reflected XSS vulnerability in index.php

### ISSUE THREAD

**Issue by jgj212** [yoya/swfed#3]
Hello:
I have find a Reflected XSS vulnerability.

The vulnerability exists due to insufficient filtration of user-supplied data in "id" HTTP parameter that will be passed to "swfed-master/www/index.php". The infected source code is line 63, there is no protection on $_REQUEST['id'], if it contains evil js code, line 67,68 will trigger untrusted code to be executed on the browser side.
![1](https://cloud.githubusercontent.com/assets/1484292/24106102/e42ee93c-0dc1-11e7-99b0-3393709eedae.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/swfed-master/www/index.php?id="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![2](https://cloud.githubusercontent.com/assets/1484292/24106454/d897e276-0dc2-11e7-9bb7-9c50f175ec4b.png)

Discoverer:  ADLab of Venustech

**Comment by yoya** [comment]
I fixed it.: https://github.com/yoya/swfed/commit/9e0c125f8fe65e494a20430183d5356d17b3c9c7
Thank you for your reporting!
