### ISSUE TITLE
A Reflected XSS vulnerability in swfimagereplace.php

### ISSUE THREAD

**Issue by jgj212** [yoya/swfed#4]
Hello:
I have find a Reflected XSS vulnerability.

The vulnerability exists due to insufficient filtration of user-supplied data in "image_id" HTTP parameter that will be passed to "swfed-master/www/swfimagereplace.php". The infected source code is line 74, there is no protection on $_REQUEST['image_id'], if it contains evil js code, line 87 will trigger untrusted code to be executed on the browser side.
![1](https://cloud.githubusercontent.com/assets/1484292/24106526/13831324-0dc3-11e7-910f-24bc608e88da.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/swfed-master/www/swfimagereplace.php?image_id="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![2](https://cloud.githubusercontent.com/assets/1484292/24106545/289e640c-0dc3-11e7-93cc-396960bcbaa7.png)

Discoverer: ADLab of Venustech

**Comment by yoya** [comment]
I fixed it.: https://github.com/yoya/swfed/commit/9e0c125f8fe65e494a20430183d5356d17b3c9c7
Thank you for your reporting!
